export const enum RouterName {
  Home = "/home",
  Info = "/info",
  Course = '/course',
  SingerCourse = '/singerCourse',
  Score = '/score',
  Exam = '/exam',
  Music = '/music',
  BBS = '/bbs',
  Song = "/song",
  Singer = "/singer",
  SongList = "/songList",
  ListSong = "/listSong",
  Comment = "/Comment",
  Consumer = "/consumer",
  Collect = "/collect",
  Error = "/404",
  SignIn = "/",
  SignOut = "0",
}
